### ISSUE TITLE
exit status not returned

### ISSUE THREAD

**Issue by timbertson** [nicoulaj/rainbow#10]
```
$ rainbow false
$ echo $?
0
```

Should be: 1

**Comment by odeblic** [comment]
Hello !
This issue looks still open.
I am working on it and will do a pull request shortly.
Cheers,
Olivier

**Comment by odeblic** [comment]
I just did my pull request. Let me know how you feel about it.

By the way, thanks for this cute project which makes my console so pretty !

Olivier

**Comment by nicoulaj** [comment]
Should be fixed in next version (2.6).
