### ISSUE TITLE
Ubuntu release key expired (and no release for 19.10)

### ISSUE THREAD

**Issue by jcassee** [nicoulaj/rainbow#123]
I was trying to install rainbow through the Ubuntu through [the openSUSE package archive](https://software.opensuse.org/download.html?project=home%3Anicoulaj%3Arainbow&package=rainbow). Unfortunately, the release key expired on October 14.

```
pub   rsa2048 2017-08-05 [SC] [verlopen op: 2019-10-14]
      A32EFC756BC1E1781FFAC74C0B002CBFCEF110F0
uid           home:nicoulaj:rainbow OBS Project <home:nicoulaj:rainbow@build.opensuse.org>
```

If you are working on Ubuntu packages, maybe also create one for Ubuntu 19.10? :slightly_smiling_face:

**Comment by nicoulaj** [comment]
It should be working now

**Comment by jcassee** [comment]
Thanks, @nicoulaj!
