### ISSUE TITLE
[RAINBOW|ERROR] 'utf-8' codec can't decode byte 0xe9 in position 89: invalid continuation byte

### ISSUE THREAD

**Issue by skitoo** [nicoulaj/rainbow#17]
Sometimes I have this error when it colorize tail result.

``` bash
rainbow -- tail -f logs/mylogs.log
```

I use Rainbow version 2.5.0

My config for tail

```
[filters]
red: .*ERROR.*|.*FATAL.*
yellow: .*WARN.*|.*WARNING.*
green: .*INFO.*
```

**Comment by nicoulaj** [comment]
I added some skipped tests.

I'm not sure what is the correct approach to handle this, especially when reading from stdin, which has a `strict` decoding policy right from the process start, so if a more experienced python developer wants to step in or give some insight, it would be great.
