### ISSUE TITLE
The following signatures were invalid: EXPKEYSIG 0B002CBFCEF110F0 home:nicoulaj:rainbow OBS Project <home:nicoulaj:rainbow@build.opensuse.org>

### ISSUE THREAD

**Issue by MaxPeal** [nicoulaj/rainbow#177]
apt update
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/nicoulaj:/rainbow/Debian_Testing  InRelease: The following signatures were invalid: EXPKEYSIG 0B002CBFCEF110F0 home:nicoulaj:rainbow OBS Project <home:nicoulaj:rainbow@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/nicoulaj:/rainbow/Debian_Testing/InRelease  The following signatures were invalid: EXPKEYSIG 0B002CBFCEF110F0 home:nicoulaj:rainbow OBS Project <home:nicoulaj:rainbow@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

apt-key list
/etc/apt/trusted.gpg.d/home_nicoulaj_rainbow.gpg
------------------------------------------------
pub   rsa2048 2017-08-05 [SC] [expired: 2021-12-10]
      A32E FC75 6BC1 E178 1FFA  C74C 0B00 2CBF CEF1 10F0
uid           [ expired] home:nicoulaj:rainbow OBS Project <home:nicoulaj:rainbow@build.opensuse.org>

**Comment by nicoulaj** [comment]
Repository has been updated, it should be fixed.

For the record package sources are here: https://build.opensuse.org/package/show/home:nicoulaj:rainbow/rainbow
