### ISSUE TITLE
debian 11 / bullseye is missing on rainbow from home:nicoulaj:rainbow project / download.opensuse.org/repositories

### ISSUE THREAD

**Issue by MaxPeal** [nicoulaj/rainbow#178]
debian 11 bullseye is missing on rainbow from home:nicoulaj:rainbow project / download.opensuse.org/repositories
debian 11 bullseye was released 2021-08-14
debian 10 Buster End of life date ~2022-08

**Comment by nicoulaj** [comment]
Repository has been updated, it should be fixed.

For the record package sources are here: https://build.opensuse.org/package/show/home:nicoulaj:rainbow/rainbow
