### ISSUE TITLE
"easy_install rainbow" fails

### ISSUE THREAD

**Issue by knapsu** [nicoulaj/rainbow#18]
When trying to install rainbow using easy_install program from Python Setup Tools I receive the following output:
...
error: Setup script exited with error: SandboxViolation: mkdir('/usr/share/rainbow', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.
...

**Comment by nicoulaj** [comment]
It should be fixed in next version (2.6).

Please note shell completion files are not installed automatically anymore, users/packagers will have to install it by themselves.
