### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by interstar** [nicoulaj/rainbow#20]
I'm trying out rainbow, which seems exactly what I need ... except : 

    $ echo "hello world" > test.txt
    $ echo "tell me about yourself" >> test.txt 
    $ cat test.txt 
    hello world
    tell me about yourself  
    $ cat test.txt | rainbow --red='.*ll.*'
    [RAINBOW|ERROR] unexpected EOF while parsing (<string>, line 1)

**Comment by khospodarysko** [comment]
@interstar Seems this is what you need:        
        rainbow --red='.*ll.*' -- cat test.txt

Sad, but it appears the project is dead. And btw I also like this tool :)

**Comment by nicoulaj** [comment]
This is fixed by #15, I'll do a release soon.
