### ISSUE TITLE
Debian package is uninstallable on `bookworm`

### ISSUE THREAD

**Issue by perlun** [nicoulaj/rainbow#203]
Hi,

When trying to set up my new machine with Debian `bookworm` (i.e. Debian 12, the current `testing` distribution) using the package here: https://software.opensuse.org/download.html?project=home%3Anicoulaj%3Arainbow&package=rainbow, I get the following error:

```shell
$ sudo apt install rainbow
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rainbow : Depends: python but it is not installable
E: Unable to correct problems, you have held broken packages.
```

On my previous machine, this worked because of the [`python-is-python2` package](https://packages.debian.org/search?keywords=python-is-python2) (available in Debian `bullseye`, i.e. Debian 11). That package `Provides: python (= 2.7.18-2)`.

Fixing this should be a matter of updating the https://build.opensuse.org/package/view_file/home:nicoulaj:rainbow/rainbow/debian.control?expand=1 file (which contains the Debian build script) and make it `Depends: python3` instead (perhaps with a minimum version if relevant).

Thanks for a nice tool! :pray:

**Comment by nicoulaj** [comment]
Thanks for reporting, it should be fixed now.

**Comment by perlun** [comment]
Looks good, thanks. :+1:
