### ISSUE TITLE
Do not bufferize

### ISSUE THREAD

**Issue by utix** [nicoulaj/rainbow#58]
Sometimes I have to add PYTHONUNBUFFERED, mainly when I launch it from vim.
IMHO BUFFERED should be deactivate by default

**Comment by nicoulaj** [comment]
Can you be more specific about the issue (steps to reproduce) ?
Do you use rainbow 2.7 ? The bufferization has been modified a lot by #23 and #57.

Setting `PYTHONUNBUFFERED` must be done before the Python interpreter is started, it is not something that can be done directly in rainbow.

**Comment by utix** [comment]
Sorry I was using a previous version (2.6), so now it is working using by setting RAINBOW_ENABLE_STDOUT
due to #5
