### ISSUE TITLE
Old builtin configs was lost

### ISSUE THREAD

**Issue by andrenmaia** [nicoulaj/rainbow#60]
In this new version (2.7.0) we don't have more the built in config `jboss.cfg`. Why not? Is that possible to include it again? 

_PS. I know almost 200 developers that use it_ :smile:

**Comment by nicoulaj** [comment]
I deleted it in 8c9f2a51dca988b6a97701ab52b2028209f9cd93 because JBoss AS does not exist anymore, do you use WildFly ? I could re-add it as it is, or rename it to wildfly...

**Comment by andrenmaia** [comment]
I'm currently working (and a lot of others developers) in a legacy project that uses JBoss AS. I know, it's sad, but it's true. For now, I got the old _cfg_ file from this commit (8c9f2a5), but you think that keep this file in the project is a bad thing? Maybe could exist another repository with all configs available. This could be a nice way to anybody create configs and share with anyone. What do you think?

**Comment by nicoulaj** [comment]
I don't think it is necessary as the project has very few users right now.
I will restore `jboss.cfg` in the next release.
